#!/usr/bin/env bash
# Publish one already-signed relay artifact set to a public immutable GitHub Release.
set -euo pipefail

readonly THIRD_PARTY_NOTICES_FILE="THIRD_PARTY_NOTICES.md"

usage() {
  cat <<'USAGE'
Usage:
  publish-github-release.sh VERSION --repo OWNER/REPO --input DIR --public-key PEM

The GitHub repository must be public and have immutable releases enabled.
The release tag is exactly VERSION. The input directory must contain four Linux
helper binaries, one ad-hoc-signed macOS app bundle, THIRD_PARTY_NOTICES.md,
manifest-VERSION.json, and manifest-VERSION.sig generated by build-release.sh
--github-repo OWNER/REPO.
This command never reads a signing private key and never overwrites an existing
release.
USAGE
}

die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

require_ed25519_public_key() {
  local path="$1"
  openssl pkey -pubin -in "$path" -text -noout 2>/dev/null | grep -Eq '^ED25519 Public-Key:' || \
    die 'release public key must be an Ed25519 public PEM'
}

require_version() {
  [[ "$1" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$ ]] || die 'VERSION must be explicit semver'
}

github_repo_valid() {
  [[ "$1" =~ ^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9][A-Za-z0-9_.-]*$ ]]
}

sha256() {
  if command -v shasum >/dev/null; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    sha256sum "$1" | awk '{print $1}'
  fi
}

decode_base64() {
  local source="$1"
  local destination="$2"
  if base64 -D < "$source" > "$destination" 2>/dev/null; then
    return 0
  fi
  base64 --decode < "$source" > "$destination" 2>/dev/null || die 'release signature is not valid base64'
}

version="${1:-}"
[[ -n "$version" ]] || { usage >&2; exit 2; }
shift
require_version "$version"

repo=""
input_dir=""
public_key=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) repo="${2:-}"; shift 2 ;;
    --input) input_dir="${2:-}"; shift 2 ;;
    --public-key) public_key="${2:-}"; shift 2 ;;
    *) usage >&2; die "unknown argument: $1" ;;
  esac
done

github_repo_valid "$repo" || die '--repo must be OWNER/REPO'
[[ -d "$input_dir" && ! -L "$input_dir" ]] || die '--input must be a regular directory'
[[ -f "$public_key" && ! -L "$public_key" ]] || die '--public-key must be a regular PEM file'
command -v gh >/dev/null || die 'GitHub CLI (gh) is required'
command -v openssl >/dev/null || die 'openssl is required'
command -v base64 >/dev/null || die 'base64 is required'
command -v shasum >/dev/null || command -v sha256sum >/dev/null || die 'sha256 tool is required'
command -v cmp >/dev/null || die 'cmp is required'
command -v jq >/dev/null || die 'jq is required for component-aware manifests'
require_ed25519_public_key "$public_key"

visibility="$(GH_PROMPT_DISABLED=1 GH_HOST=github.com gh api "repos/${repo}" --jq .visibility)" || \
  die 'GitHub authentication cannot read the selected release repository'
[[ "$visibility" == "public" ]] || \
  die 'GitHub release repository must be public'

manifest="${input_dir}/manifest-${version}.json"
signature="${input_dir}/manifest-${version}.sig"
notices="${input_dir}/${THIRD_PARTY_NOTICES_FILE}"
artifacts=(
  opencodex-relay_linux_amd64
  opencodex-relay_linux_arm64
  opencodex-relayctl_linux_amd64
  opencodex-relayctl_linux_arm64
  OpenCodexRelay.app.zip
)
for file in "$manifest" "$signature" "$notices"; do
  [[ -f "$file" && ! -L "$file" ]] || die "required release file is unavailable: $file"
done
for file in "${artifacts[@]}"; do
  [[ -f "${input_dir}/${file}" && ! -L "${input_dir}/${file}" ]] || \
    die "required release artifact is unavailable: ${input_dir}/${file}"
done

tmp="$(mktemp -d "${TMPDIR:-/tmp}/opencodex-relay-release-publish.XXXXXX")"
trap 'rm -rf -- "$tmp"' EXIT
signature_binary="${tmp}/manifest.sig.bin"
decode_base64 "$signature" "$signature_binary"
openssl pkeyutl -verify -pubin -inkey "$public_key" -rawin \
  -in "$manifest" -sigfile "$signature_binary" >/dev/null || \
  die 'release manifest signature is invalid'
jq -e --arg version "$version" '
  .version == $version
  and .compatibility_revision == 4
  and (.artifacts | type == "array" and length == 5)
  and (keys | sort == ["artifacts", "compatibility_revision", "documents", "version"])
' "$manifest" >/dev/null || die 'release manifest is not a complete revision 4 artifact set'

manifest_artifact_matches() {
  local os="$1"
  local arch="$2"
  local component="$3"
  local file="$4"
  local expected_url="https://github.com/${repo}/releases/download/${version}/${file}"
  jq -e \
    --arg os "$os" --arg arch "$arch" --arg component "$component" \
    --arg file "$file" --arg url "$expected_url" '
      [.artifacts[] | select(
        .os == $os and .arch == $arch and .component == $component and
        .file == $file and .url == $url and (.sha256 | test("^[0-9a-f]{64}$")) and
        (if $os == "darwin" then true else
          (keys | sort == ["arch", "component", "file", "os", "sha256", "url"])
        end)
      )] | length == 1
    ' "$manifest" >/dev/null
}
manifest_artifact_matches linux amd64 relay opencodex-relay_linux_amd64 || die 'manifest is missing linux/amd64 relay'
manifest_artifact_matches linux amd64 relayctl opencodex-relayctl_linux_amd64 || die 'manifest is missing linux/amd64 relayctl'
manifest_artifact_matches linux arm64 relay opencodex-relay_linux_arm64 || die 'manifest is missing linux/arm64 relay'
manifest_artifact_matches linux arm64 relayctl opencodex-relayctl_linux_arm64 || die 'manifest is missing linux/arm64 relayctl'
manifest_artifact_matches darwin arm64 macos_menu_bar_bundle OpenCodexRelay.app.zip || die 'manifest is missing macOS MenuBar bundle'
jq -e '
  [.artifacts[] | select(.component == "macos_menu_bar_bundle")]
  | length == 1 and .[0].bundle_id == "io.github.novelkr.opencodex-relay"
  and .[0].signing_mode == "adhoc"
  and (.[0] | keys | sort == ["arch", "bundle_id", "component", "file", "os", "sha256", "signing_mode", "url"])
' "$manifest" >/dev/null || die 'manifest macOS bundle signing metadata is invalid'

verify_local_artifact_hash() {
  local file="$1"
  local expected
  local actual
  expected="$(jq -er --arg file "$file" '
    [.artifacts[] | select(.file == $file) | .sha256]
    | if length == 1 then .[0] else empty end
  ' "$manifest")" || die "manifest has no unique hash for ${file}"
  actual="$(sha256 "${input_dir}/${file}")"
  [[ "$actual" == "$expected" ]] || die "local release artifact hash does not match the signed manifest: ${file}"
}
for file in "${artifacts[@]}"; do
  verify_local_artifact_hash "$file"
done
notices_hash="$(sha256 "$notices")"
expected_notices_url="https://github.com/${repo}/releases/download/${version}/${THIRD_PARTY_NOTICES_FILE}"
grep -F "\"documents\":[{\"file\":\"${THIRD_PARTY_NOTICES_FILE}\",\"url\":\"${expected_notices_url}\",\"sha256\":\"${notices_hash}\"}]" "$manifest" >/dev/null || \
  die 'manifest does not bind THIRD_PARTY_NOTICES.md to the selected public GitHub release'

if GH_PROMPT_DISABLED=1 GH_HOST=github.com gh release view "$version" --repo "$repo" >/dev/null 2>&1; then
  die "GitHub release ${repo}@${version} already exists; releases are never overwritten"
fi

release_files=("$manifest" "$signature" "$notices")
for file in "${artifacts[@]}"; do
  release_files+=("${input_dir}/${file}")
done
expected_assets=("$(basename -- "$manifest")" "$(basename -- "$signature")" "$THIRD_PARTY_NOTICES_FILE" "${artifacts[@]}")

verify_release_assets() {
  local expected_draft="$1"
  local actual_assets="${tmp}/actual-assets"
  local expected_assets_file="${tmp}/expected-assets"
  local is_draft
  is_draft="$(GH_PROMPT_DISABLED=1 GH_HOST=github.com gh release view "$version" --repo "$repo" \
    --json isDraft --jq '.isDraft')" || die 'unable to read back GitHub release draft state'
  [[ "$is_draft" == "$expected_draft" ]] || die 'GitHub release draft state is unexpected'
  GH_PROMPT_DISABLED=1 GH_HOST=github.com gh release view "$version" --repo "$repo" \
    --json assets --jq '.assets[].name' | LC_ALL=C sort > "$actual_assets" || \
    die 'unable to read back GitHub release assets'
  printf '%s\n' "${expected_assets[@]}" | LC_ALL=C sort > "$expected_assets_file"
  cmp -s "$expected_assets_file" "$actual_assets" || \
    die 'GitHub release asset set is incomplete or unexpected'
}

release_notes_template="${tmp}/release-notes.template.md"
release_notes="${tmp}/release-notes.md"
cat > "$release_notes_template" <<'RELEASE_NOTES'
# OpenCodex Relay __VERSION__

OpenCodex Relay connects Codex CLI and Desktop clients to a self-hosted OpenCodex endpoint through a device-local compatibility relay. This release provides the reviewed macOS and Linux client artifacts for version `__VERSION__`.

## Choose your download

| Platform | Download |
| --- | --- |
| Apple Silicon, macOS 26+ | `OpenCodexRelay.app.zip` |
| Linux amd64 | `opencodex-relay_linux_amd64` and `opencodex-relayctl_linux_amd64` |
| Linux arm64 | `opencodex-relay_linux_arm64` and `opencodex-relayctl_linux_arm64` |

Linux installations need both the relay daemon and the matching `relayctl` control tool.

## Install or update

- macOS users should expand the app archive, open the app, and follow the [Relay guide](https://github.com/__REPOSITORY__/blob/__VERSION__/client/relay/README.md).
- Linux users should use the manifest-verifying installer described in the [Relay guide](https://github.com/__REPOSITORY__/blob/__VERSION__/client/relay/README.md).
- Existing installations should follow the reviewed [update and rollback runbook](https://github.com/__REPOSITORY__/blob/__VERSION__/docs/updates.md).

## Security and verification

Public GitHub Actions built and independently verified all eight release assets before publication. The signed revision 4 manifest binds every downloadable runtime artifact and `THIRD_PARTY_NOTICES.md` to its SHA-256 digest. Verify the manifest with the tracked [v2 Ed25519 public key](https://github.com/__REPOSITORY__/blob/__VERSION__/config/trust/opencodex-relay-release-ed25519.pub).

Each asset also has GitHub build provenance bound to this tag:

```bash
gh attestation verify FILE --repo __REPOSITORY__ \
  --source-ref refs/tags/__VERSION__
```

## macOS first launch

The macOS app is ad-hoc signed with the Hardened Runtime. It is not Developer ID signed or notarized. On first launch, open **System Settings → Privacy & Security**, choose **Open Anyway** for OpenCodexRelay, then confirm **Open**. Do not remove quarantine attributes or disable Gatekeeper.

## Source

This immutable release was built from the public [`__VERSION__` source tag](https://github.com/__REPOSITORY__/tree/__VERSION__).
RELEASE_NOTES
sed -e "s|__VERSION__|${version}|g" -e "s|__REPOSITORY__|${repo}|g" \
  "$release_notes_template" > "$release_notes"

GH_PROMPT_DISABLED=1 GH_HOST=github.com gh release create "$version" "${release_files[@]}" \
  --repo "$repo" --draft --latest=false --title "OpenCodex Relay ${version}" \
  --notes-file "$release_notes" >/dev/null || \
  die 'unable to create draft GitHub release'
verify_release_assets true
GH_PROMPT_DISABLED=1 GH_HOST=github.com gh release edit "$version" --repo "$repo" \
  --draft=false --latest=false >/dev/null || die 'unable to publish GitHub release'
verify_release_assets false
if [[ "$(GH_PROMPT_DISABLED=1 GH_HOST=github.com gh release view "$version" --repo "$repo" \
  --json isDraft,isImmutable --jq '[.isDraft, .isImmutable] | @tsv')" != $'false\ttrue' ]]; then
  # GitHub exposes immutable status only after publication. Do not leave the
  # newly-created release public when that postcondition cannot be confirmed.
  GH_PROMPT_DISABLED=1 GH_HOST=github.com gh release delete "$version" --repo "$repo" --yes >/dev/null || \
    die 'release immutability was not confirmed and automatic deletion of the new public release failed; remove it manually before enrolling clients'
  die 'release immutability was not confirmed; the newly-created public release was deleted'
fi

printf 'github_release=%s tag=%s immutable=true\n' "$repo" "$version"
